version: 2
jobs:
  x86_build:
    docker:
      - image: ubuntu:bionic
    steps:
      - checkout
      - run:
          name: Update apt
          command: apt-get update
      - run:
          name: Install Toolchain
          command: apt-get install -y g++-7 cmake ninja-build git wget postgresql-10
      - run:
          environment:
            CXX: g++-7
          name: Generate Project
          command: mkdir build && cd build && cmake ..
      - run:
          working_directory: build/
          name: Build Project
          command: make
      - run:
          working_directory: build/tests
          name: Run Tests (basic)
          command: ./basic_tests
      - run:
          working_directory: build/tests
          name: Run Tests (msgpack_json)
          command: ./msgpack_json_tests
      - run:
          working_directory: build/tests
          name: Run Tests (parallelism)
          command: ./parallelism_tests
workflows:
  version: 2
  all_platforms:
    jobs:
      - x86_build
